### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [mrts/foodbank-campaign#7]
Hi @mrts , I'm a graphic designer, I have reviewed your project and it looks good. That's why I want to design a logo for your project. What do you think?

**Comment by mrts** [comment]
Hello @zularizal ! Thank you, very kind offer! This application is used by Estonian Foodbank and they already have a logo, see the test environment with the logo here: https://test-osale.toidupank.ee/ . But I'll keep your offer in mind, maybe I'll bump into another case where your help would be needed.
